background                = "#0d110e"
background-alpha          = 0.96
text                      = "#c9d2cc"
border                    = "rgba(2fe07bcc) rgba(12633d99) 45deg"
border-alpha              = 0.48
scrim                     = "#050706"
scrim-alpha               = 0.56
selected-background       = "#2fe07b"
selected-background-alpha = 0.11
selected-text             = "#49f397"
selected-border           = "#2fe07b"
selected-border-alpha     = 0.78
selected-border-width     = "1 1 1 3"
