background       = "#090c0a"
background-alpha = 0.80
text             = "#dce4df"
placeholder      = "#718077"
text-error       = "#ed7f84"
border           = "#274136"
border-active    = "rgba(49f397ff) rgba(2fe07bdd) 45deg"
border-error     = "#cf666b"
border-alpha     = 0.94
border-width     = 1
border-active-width-left = 4
border-error-width-left  = 4
selection        = "#49f397"
selection-alpha  = 0.48
